name: Deploy Windows Exe

on:
  workflow_dispatch:

jobs:
  deploy_windows_exe:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Clone gtest library
        run: 'git clone https://github.com/google/googletest.git'
      - name: Build project
        run: |
          cmake .
          cmake --build . --config Release
      - name: Test project
        run: ctest
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          tag_name: 'Release'
          release_name: 'Release Windows Exe'
          draft: false
          prerelease: false
      - name: Upload Release Asset Windows
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          upload_url: '${{ steps.create_release.outputs.upload_url }}'
          asset_path: './Release/IPFilter.exe'
          asset_name: 'IPFilter-Windows.exe'
          asset_content_type: application/octet-stream